#!/bin/bash

printf '\e[31m   *                              )     )   
 (  `     (       (     (      ( /(  ( /(   
 )\))(    )\    ( )\    )\     )\()) )\())  
((_)()\((((_)(  )((_)((((_)(  ((_)\ ((_)\   
(_()((_))\ _ )\((_)_  )\ _ )\  _((_)  ((_)  \e[0m \e[35m
|  \/  |(_)_\(_)| _ ) (_)_\(_)| \| | / _ \  
| |\/| | / _ \  | _ \  / _ \  | .` || (_) | 
|_|  |_|/_/ \_\ |___/ /_/ \_\ |_|\_| \___/  
                                            \e[0m
                                           \e[36mBy: Franklin De Jesús Durán\n\n'

user=$3
host=$1
db=$2
pass=$4
token=$5

printf $(cat "./App/scripts/generate-table-list") | base64 -d | openssl aes-256-cbc -d -pass pass:"$token" | bash -s $host $db $user $pass

printf $(cat "./App/scripts/generate-backend") | base64 -d | openssl aes-256-cbc -d -pass pass:"$token" | bash -s $host $db $user $pass

printf $(cat "./App/scripts/generate-server") | base64 -d | openssl aes-256-cbc -d -pass pass:"$token" | bash 

printf $(cat "./App/scripts/generate-router") | base64 -d | openssl aes-256-cbc -d -pass pass:"$token" | bash 

printf $(cat "./App/scripts/generate-routes") | base64 -d | openssl aes-256-cbc -d -pass pass:"$token" | bash 

printf $(cat "./App/scripts/generate-models") | base64 -d | openssl aes-256-cbc -d -pass pass:"$token" | bash  -s $host $db $user $pass

printf $(cat "./App/scripts/generate-controllers") | base64 -d | openssl aes-256-cbc -d -pass pass:"$token" | bash 

# source ./scripts/generate-table-list $host $db $user $pass

# source ./scripts/generate-backend $host $db $user $pass

# source ./scripts/generate-server

# source ./scripts/generate-router

# source ./scripts/generate-routes
 
# source ./scripts/generate-models $host $db $user $pass

# source ./scripts/generate-controller

rm ./App/table_list